apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  labels:
    version: "1.10"
spec:
  replicas: 3
  selector:
    matchLabels:
      version: "1.10"
  template:
    metadata:
      labels:
        version: "1.10"
    spec:
      containers:
      - name: nginx
        image: nginx:1.11
        ports:
        - containerPort: 8
