apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  labels:
    version: "1.12"
spec:
  replicas: 3
  selector:
    matchLabels:
      version: "1.12"
  template:
    metadata:
      labels:
        version: "1.12"
    spec:
      containers:
      - name: nginx
        image: nginx:1.12
        ports:
        - containerPort: 80
